package it.cloud.amazon.ec2;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Properties;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.amazonaws.auth.AWSCredentials;
import com.amazonaws.auth.PropertiesCredentials;

public class Configuration {
	
	private static final Logger logger = LoggerFactory.getLogger(Configuration.class);
	
	public static AWSCredentials AWS_CREDENTIALS = null;
	public static String REGION = "us-west-1";
	
	public static String SECURITY_GROUP_NAME = "CloudRunnerSG";
	public static String SECURITY_GROUP_DESC = "Security Group generated by cloud-runner";
	
	public static final String CREDENTIALS = "credentials.properties";
	public static final String CONFIGURATION = "configuration.properties";
	public static final String FIREWALL_RULES = "firewallrules.csv";

	public static final String SECURITY_GROUP_FILE_NAME = "securitygroupcreated.txt";
	
	static {
		try {
			loadConfiguration(CONFIGURATION);
		} catch (Exception e) {
			logger.error("Error while configuring the system.", e);
		}
		
		try {
			AWS_CREDENTIALS = new PropertiesCredentials(getInputStream(CREDENTIALS));
		} catch (Exception e) {
			AWS_CREDENTIALS = null;
		}
	}
	
	public static InputStream getInputStream(String filePath) {
		File f = new File(filePath);
		if (f.exists())
			try {
				return new FileInputStream(f);
			} catch (Exception e) { }
		
		InputStream is = Configuration.class.getResourceAsStream(filePath);
		if (is == null)
			is = Configuration.class.getResourceAsStream("/" + filePath);
		return is;
	}
	
	public static Path getPathToFile(String filePath) {
		File f = new File(filePath);
		if (f.exists())
			try {
				return f.toPath();
			} catch (Exception e) { }
		
		URL url = Configuration.class.getResource(filePath);
		if (url == null)
			url = Configuration.class.getResource("/" + filePath);
		if (url == null)
			return null;
		else
			return Paths.get(url.getPath());
	}
	
	public static void saveConfiguration(String filePath) throws IOException {
		FileOutputStream fos = new FileOutputStream(filePath);
		Properties prop = new Properties();
		
		prop.put("REGION", REGION);
		prop.put("SECURITY_GROUP_NAME", SECURITY_GROUP_NAME);
		
		prop.store(fos, "CloudRunner configuration properties");
		fos.flush();
	}
	
	public static void loadConfiguration(String filePath) throws IOException {
		Properties prop = new Properties();
		InputStream is = getInputStream(filePath);
		prop.load(is);
		
		REGION = prop.getProperty("REGION", REGION);
		SECURITY_GROUP_NAME = prop.getProperty("SECURITY_GROUP_NAME", SECURITY_GROUP_NAME);
	}
	
	public static List<String> checkValidity() {
		ArrayList<String> errors = new ArrayList<String>();
		
		return errors;
	}
}
